[build]
base = "LuMInA-2k25"                       # <-- folder where package.json exists
command = "npm install && npm run build && npm run export"
publish = "LuMInA-2k25/out"                # <-- exported static folder

[build.environment]
NODE_VERSION = "18"
